base_model: mutant_c0_p0_o1
merge_method: ties
models:
- model: mutant_c0_p0_o1
  parameters:
    weight: 1.0
- model: Qwen/Qwen2.5-0.5B-Instruct
  parameters:
    weight: 1.0
parameters:
  density: 0.9
